### PR TITLE
Add Bullet

### PR DESCRIPTION
**Pull request by chapulina**
Bullet support was added in https://github.com/ignitionrobotics/ign-physics/pull/208, see https://github.com/ignitionrobotics/ign-physics/issues/44

### CODE REVIEW

**Comment by j-rivero** [comment]
A couple of things I think are missing:
  * bullet inside the build deps 555844a 
  * install files are needed to indicate the packaging which files go into the new packages 60ffbf3

**Review by j-rivero — APPROVED** [review]
we might need a prerelease to check that bullet is well packaged, we are to good to test IMHO

**Comment by chapulina** [comment]
> bullet inside the build deps 555844a

I didn't do this originally on purpose, so current users of `ignition-physics3` don't get a new dependency without opting-in. Is there a way to accomplish this?

> Install files are needed to indicate the packaging which files go into the new packages 60ffbf3

Ahh thanks, I had done all that, but I didn't add the files :woman_facepalming:

**Comment by j-rivero** [comment]
> > bullet inside the build deps [555844a](https://github.com/ignition-release/ign-physics3-release/commit/555844a75b84137f9954e28ed928927175d1f9ab)
> 
> I didn't do this originally on purpose, so current users of `ignition-physics3` don't get a new dependency without opting-in. Is there a way to accomplish this?

build-deps (the ones at the top of the control) are only being used when building, in our case in the Jenkins jobs. Should not affect final users.

**Comment by chapulina** [comment]
Gotcha, thanks for the clarification :+1:

**Pull request merged**
